
pipeline{
   agent any 

   tools{
    maven 'M2_HOME'
   }

   stages{

    stage('sonar scan'){
        steps{
           withSonarQubeEnv('SonarQube'){
            sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=roberttemta_geo-application'
           }
            
        }
    }
    stage("maven"){
        steps{
            sh 'mvn clean' 
            sh 'mvn validate'
            sh 'mvn compile'
            sh 'mvn install'
            sh 'mvn package'
            sh 'mvn test'
        }
    }

    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
            target/bio*.jar \
            "http://ec2-100-26-155-211.compute-1.amazonaws.com:8081/artifactory/geo-location/geo/bio_${BUILD_ID}.jar"'
        }
    }

   }
}