
pipeline{
   agent any 

   tools{
    maven 'M2_HOME'
   }

   stages{
    stage("maven"){
        steps{
            sh 'mvn clean validate compile install package test'
        }
    }

    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
            target/bio*.jar \
            "http://ec2-100-26-155-211.compute-1.amazonaws.com:8081/artifactory/geo-location/geo/bio_${BUILD_ID}.jar"'
        }
    }

   }
}